//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leadership.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionOption
    {
        public int Id { get; set; }
        public string TypeLanguage { get; set; }
        public Nullable<int> FormId_fk { get; set; }
        public Nullable<int> QuestionId_fk { get; set; }
        public string QuestionCode { get; set; }
        public string OptionTypeValidation { get; set; }
        public string HindiOptionText { get; set; }
        public string LabelName1 { get; set; }
        public string LabelName2 { get; set; }
        public string OptionText { get; set; }
        public string OptionCode { get; set; }
        public string ControlInputType { get; set; }
        public string ControlInputType1 { get; set; }
        public string InputType { get; set; }
        public string InputType1 { get; set; }
        public string Limit { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
