//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leadership.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionBook
    {
        public int Id { get; set; }
        public Nullable<int> FormId_fk { get; set; }
        public string TypeLanguage { get; set; }
        public string QuestionCode { get; set; }
        public string HindiQuestion { get; set; }
        public string Question { get; set; }
        public string QuestionType { get; set; }
        public string SectionType { get; set; }
        public string ControlType { get; set; }
        public string ControlInputType { get; set; }
        public string QuestTypeValidation { get; set; }
        public string ParentQuestionCode { get; set; }
        public string DependedAnswer { get; set; }
        public string Frequency { get; set; }
        public string ReportingBy { get; set; }
        public string AnswerCode { get; set; }
        public string Limit { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsRepeat { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public string DisplayIndicator { get; set; }
        public string ExtraOne { get; set; }
        public Nullable<bool> IsQuestionDisplay { get; set; }
    }
}
