//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leadership.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Survey
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Survey()
        {
            this.tbl_SurveyAnswer = new HashSet<tbl_SurveyAnswer>();
        }
    
        public int Id { get; set; }
        public Nullable<int> FormId { get; set; }
        public Nullable<int> SchoolId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> YearId { get; set; }
        public Nullable<int> FrequencyId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SurveyAnswer> tbl_SurveyAnswer { get; set; }
    }
}
